package project.vilsoncake.Flowt.entity.enumerated;

public enum Genre {
    ROCK, POP, HIP_HOP, RAP, CLASSICAL, JAZZ, ELECTRONIC, TECHNO, METAL, PUNK, COUNTRY, BLUES, REGGAE, FUNK, SOUL, DISCO, RHYTHM_AND_BLUES, INDIE, ALTERNATIVE, LATIN, CLUB, DUBSTEP, DRUM_AND_BASS, TRANCE, DUB, DABBLE_ROCK, CHANSON, RAPCORE
}
